### ISSUE TITLE
Manca impl caso nickname esistente nel DB

### ISSUE THREAD

**Issue by FedericoRez** [ManuelBava/KeZapp-Gal#3]
Non sappiamo come prendere la l'id dell'utente nel DB e assegnarla alla sessione locale ...

a1b992e2bdbbad04af58bc69e9008fbdac08d90b

**Comment by luca-lezzerini** [comment]
Non deve essere creata la Chat e ritornato un DTO vuoto, ossia con contatti senza elementi, nessuna sessione, lista messaggi senza elementi

**Comment by luca-lezzerini** [comment]
Il client deve segnalare un messaggio di errore che indichi che non ha ricevuto la sessione e di riprovare di nuovo
