### ISSUE TITLE
Non sappiamo come implementare registrazione nel caso in cui l'utente esiste nel DB

### ISSUE THREAD

**Issue by FedericoRez** [ManuelBava/KeZapp-Gal#4]
Non sappiamo come implementare registrazione nel caso in cui l'utente esiste nel DB

**Comment by luca-lezzerini** [comment]
Non deve essere creata la Chat e ritornato un DTO vuoto, ossia con contatti senza elementi, nessuna sessione, lista messaggi senza elementi

Il client deve segnalare un messaggio di errore che indichi che non ha ricevuto la sessione e di riprovare di nuovo
