### ISSUE TITLE
Non sappiamo come assegnare id alla sessione locale nel metodo richiediRegistrazione

### ISSUE THREAD

**Issue by FedericoRez** [ManuelBava/KeZapp-Gal#5]
Non sappiamo come assegnare id alla sessione locale

**Comment by luca-lezzerini** [comment]
Save ritorna l'oggetto salvato su DB con la chiave generata dal DB stesso. Mettere questo valore in una variabile Chat da cui prendere l'id, convertirla in stringa, metterla in sessione e poi aggiornare il DB, usando sempre save
