### ISSUE TITLE
errore command execution failed

### ISSUE THREAD

**Issue by Iappelli-Leonardo** [ManuelBava/KeZapp-Gal#7]
![Cattura1](https://user-images.githubusercontent.com/78487482/109806065-895a5e80-7c24-11eb-96a0-1082c42746ca.PNG)
![Cattura](https://user-images.githubusercontent.com/78487482/109806073-8b242200-7c24-11eb-81cc-442c2fa8a711.PNG)

**Comment by luca-lezzerini** [comment]
Server DB spento.
Oppure utente DB sbagliato: dbuser@password?
